import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Header/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Next Me',
  description: 'Generated by Next js',
}

 const RootLayout = ({ children }) =>{
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        {children}
        </body>
    </html>
  )
}
export default RootLayout;