import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Next Me',
  description: 'Generated by Next js',
}

 const RootLayout = ({ children }) =>{
  return (
    <html lang="en">
      <body className={inter.className}>
        <h2>Hello 2</h2>
        {children}
        </body>
    </html>
  )
}
