import React from 'react';
export const metadata = {
    title: 'Blog',
    description: 'Generated by Next js',
  }
const BlogPage = () => {
    return (
        <div>
            <h2>I am blog page</h2>
        </div>
    );
};

export default BlogPage;