import React from 'react';
export const metadata = {
    title: 'Blog',
    description: 'Generated by Next js',
  }
const BlogPage = ({params}) => {
    const [year, music] = params.segments || [];
    return (
        <div>
            <h2>I am blog page{year || new Date().getFullYear()}</h2>
        </div>
    );
};

export default BlogPage;